services:
  - type: web
    name: usf-pnl
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /ping
    healthCheckInterval: 15
    healthCheckTimeout: 10
    healthCheckRetries: 3
    autoDeploy: false
    envVars:
      - key: PORT
        value: "10000"
      - key: PANEL_PASSWORD
        sync: false